# <font face = 'Impact' color = '#FFAEBC' > Exercise on Loading, Organizing, and Storing Data<font/>
#### <font face = 'Times New Roman' color = '#B5E5CF'> Licence: GPL v3.0 <font/>
#### <font face = 'Times New Roman' color = '#B5E5CF'> Author and Trainer: Paolo Hilado MSc. (Data Science) <font/>
Showcase your learning and skills by accomplishing this jupyter notebook. Follow through each of the tasks and code with python to address them.

In [11]:
 #Submitted by: Sheena Salao
 # Year Level & Section: 4-B
 #Date: September 5, 2025

In [30]:
# Import the necesary libraries such as pandas, researchpy, os, and numpy.
import pandas as pd
import numpy as np
import os

In [12]:
#Checking out the current working directory
print(os.getcwd())

/content/sample_data

In [13]:
os.chdir('/content/sample_data')

In [14]:
#Load a spreadsheet and assigning it to a variable df.
# Open and work on "ExperimentOne.xlsx".
import pandas as pd
df = pd.read_excel("ExperimentOne.xlsx")
df

    ID   Post  Group
0    1  17.23  Cntrl
1    2  16.04  Cntrl
2    3  19.22  Cntrl
3    4  19.45  Cntrl
4    5  18.53  Cntrl
..  ..    ...    ...
69  70   6.86     Tx
70  71  17.63     Tx
71  72  18.84     Tx
72  73  15.11     Tx
73  74  19.07     Tx

[74 rows x 3 columns]

In [5]:
#View the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      74 non-null     int64
 1   Post    74 non-null     float64
 2   Group   74 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.9+ KB

In [6]:
# Viewing the first 7 rows
df.head(7)

   ID   Post  Group
0   1  17.23  Cntrl
1   2  16.04  Cntrl
2   3  19.22  Cntrl
3   4  19.45  Cntrl
4   5  18.53  Cntrl
5   6  21.00  Cntrl
6   7  19.28  Cntrl

In [7]:
# Viewing the last 7 rows
df.tail(7)

    ID   Post Group
67  68  12.55    Tx
68  69  19.67    Tx
69  70   6.86    Tx
70  71  17.63    Tx
71  72  18.84    Tx
72  73  15.11    Tx
73  74  19.07    Tx

In [16]:
# Slice the data frame to only show the data on the "Post" Column.
sub = df.loc[:, 'Post']
print(sub)

0     17.23
1     16.04
2     19.22
3     19.45
4     18.53
      ...
69     6.86
70    17.63
71    18.84
72    15.11
73    19.07
Name: Post, Length: 74, dtype: float64

In [18]:
# Create different subsets of the data frame and show it.
# Get the data for the first column
first_column = df.iloc[:, 0]
first_column

0      1
1      2
2      3
3      4
4      5
      ..
69    70
70    71
71    72
72    73
73    74
Name: ID, Length: 74, dtype: int64

In [22]:
# Get the Post Test and Group data for records 1-10
post_group = df.loc[0:9, ['Post', 'Group']]
post_group

    Post  Group
0  17.23  Cntrl
1  16.04  Cntrl
2  19.22  Cntrl
3  19.45  Cntrl
4  18.53  Cntrl
5  21.00  Cntrl
6  19.28  Cntrl
7  19.63  Cntrl
8  12.66  Cntrl
9  17.55  Cntrl

In [20]:
Subsets = df.loc[0:9, ['Post', 'Group']]
Subsets

    Post  Group
0  17.23  Cntrl
1  16.04  Cntrl
2  19.22  Cntrl
3  19.45  Cntrl
4  18.53  Cntrl
5  21.00  Cntrl
6  19.28  Cntrl
7  19.63  Cntrl
8  12.66  Cntrl
9  17.55  Cntrl

In [19]:
# Get the Post Test and Group data for records 7,11,15,50,61.
post_group = df.loc[[6,10,14,50,60], ['Post', 'Group']]
post_group

     Post  Group
6   19.28  Cntrl
10  18.08  Cntrl
14  19.93  Cntrl
50  18.58     Tx
60  16.10     Tx

In [21]:
# Check the information of the data frame such as number of records and features,
# data types of each feature and file size.
df_info = df.info()
df_info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      74 non-null     int64
 1   Post    74 non-null     float64
 2   Group   74 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.9+ KB

In [23]:
#Checking for NAs or missing cases for the data set
df.isnull().values.any()

np.False_

In [24]:
# Check for NAs per column
missing_values = df.isnull().sum()
missing_values

ID       0
Post     0
Group    0
dtype: int64

In [37]:
# Provide a descriptive analysis for the Post Test measure
desc1 = df.describe()
desc2 = df['Post'].describe()

In [35]:
desc1.T

      count       mean        std   min     25%     50%    75%    max
ID     74.0  37.500000  21.505813  1.00  19.250  37.500  55.75  74.00
Post   74.0  16.924324   3.344020  5.28  16.055  18.205  19.16  21.04

In [34]:
desc2.T

count    74.000000
mean     16.924324
std       3.344020
min       5.280000
25%      16.055000
50%      18.205000
75%      19.160000
max      21.040000
Name: Post, dtype: float64

In [39]:
# Provide a descriptive analysis for Post Test measure per Group.
# Make sure that it is rounded to two decimal places only.
# Save this in the variable labeled results.
# Present the results variable

desc_resut = df.groupby('Group')['Post'].describe().round(2)
desc_resut

       count   mean   std   min    25%    50%    75%    max
Group
Cntrl   37.0  17.23  3.52  5.28  16.24  19.05  19.42  21.04
Tx      37.0  16.62  3.17  6.86  16.01  17.63  18.55  20.83

Journal on Activity: Exercise One
  
  
What were the problems that you encountered while accomplishment this exercise?
    
- there are some problems that I've encounter while doing the exercise, I sometimes got confuse, especially in viewing the asked columns or rows, also when I need to get the specific data asked. In this confusion my work often tend to get errors.

Cite the reasons why you had these problems while doing the task.
- as what I have mentioned above, one reason is the confusion

List down your next set of actions so as not to encounter these problems again.
- familiarize the functions and structure
- be careful/double check the characters to avoid errors